"""Compaction scaling benchmark via llama-server continuous batching."""
import json
import os
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed

SERVER_URL = "http://127.0.0.1:9095"
N_PREDICT = 50
N_SLOTS = 2  # match server config
TMP = os.environ.get('TEMP', '/tmp')

# Prompt file paths (generated by gen-prompts.py)
PROMPT_CONFIGS = {
    '1k': {'full_tokens': 881},
    '10k': {'full_tokens': 10500},
}

RATIOS = [
    ('1x',    100),
    ('1.25x',  80),
    ('1.67x',  60),
    ('2.5x',   40),
    ('5x',     20),
    ('10x',    10),
    ('20x',     5),
    ('50x',     2),
]


def send_completion(payload_bytes):
    """Send a completion request, return parsed JSON."""
    req = urllib.request.Request(
        f"{SERVER_URL}/completion",
        data=payload_bytes,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            return json.loads(resp.read())
    except Exception as e:
        return {"error": str(e)}


def bench_concurrent(payload_bytes, n_concurrent):
    """Fire n_concurrent requests and return aggregate results."""
    results = []
    t0 = time.perf_counter()
    with ThreadPoolExecutor(max_workers=n_concurrent) as pool:
        futures = [pool.submit(send_completion, payload_bytes) for _ in range(n_concurrent)]
        for f in as_completed(futures):
            results.append(f.result())
    elapsed = time.perf_counter() - t0

    total_tokens = 0
    errors = 0
    per_slot_tps = []
    for r in results:
        t = r.get('timings', {})
        n = t.get('predicted_n', 0)
        tps = t.get('predicted_per_second', 0)
        if n > 0:
            total_tokens += n
            per_slot_tps.append(tps)
        else:
            errors += 1

    agg_tps = total_tokens / elapsed if elapsed > 0 else 0
    return {
        'total_tokens': total_tokens,
        'elapsed_s': elapsed,
        'agg_tps': agg_tps,
        'errors': errors,
        'per_slot_tps': per_slot_tps,
    }


def main():
    # Check server health
    try:
        with urllib.request.urlopen(f"{SERVER_URL}/health", timeout=5) as r:
            health = json.loads(r.read())
        if health.get('status') != 'ok':
            print(f"Server not ready: {health}")
            sys.exit(1)
    except Exception as e:
        print(f"Cannot reach server at {SERVER_URL}: {e}")
        sys.exit(1)

    print(f"=== KV Compaction Scaling Benchmark ===")
    print(f"Model: SmolLM3 3B Q4_K_M (Vulkan)")
    print(f"Slots: {N_SLOTS}, gen: {N_PREDICT} tokens")
    print()

    prompt_sizes = sys.argv[1:] if len(sys.argv) > 1 else ['1k']
    for ps in prompt_sizes:
        ft = PROMPT_CONFIGS[ps]['full_tokens']
        print(f"--- Prompt: {ps} ({ft} tokens) ---")
        print(f"{'Ratio':<7} {'KV tok':<7} {'Agg tok/s':<10} {'Per-slot':<10} {'Err':<4}")
        print(f"{'-----':<7} {'------':<7} {'---------':<10} {'--------':<10} {'---':<4}")

        for ratio_label, keep_pct in RATIOS:
            kv_tokens = int(ft * keep_pct / 100)
            req_file = os.path.join(TMP, f"req_{ps}_keep{keep_pct}.json")

            if not os.path.exists(req_file):
                print(f"{ratio_label:<7} {kv_tokens:<7} NO_FILE")
                continue

            with open(req_file, 'rb') as f:
                payload = f.read()

            # Warmup (single request)
            send_completion(payload)

            # Benchmark
            r = bench_concurrent(payload, N_SLOTS)
            avg_slot = sum(r['per_slot_tps']) / len(r['per_slot_tps']) if r['per_slot_tps'] else 0

            err_str = str(r['errors']) if r['errors'] > 0 else ""
            print(f"{ratio_label:<7} {kv_tokens:<7} {r['agg_tps']:<10.1f} {avg_slot:<10.1f} {err_str:<4}")
            sys.stdout.flush()

        print()

    print("=== Done ===")


if __name__ == '__main__':
    main()
